name: Report stale branch

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 6 * * 1-5"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Report stale branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Report stale branches
        uses: mn185177/report-stale-branches@main
        id: delete_stuff
      - name: Group of log lines
        run: |
            echo "branch_updates= ${{ steps.delete_stuff.outputs.deleted_branches }}" | tr "-" "\n"
      - name: Post to a slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          #channel-id: 'sre-git-alerts'
          slack-message: "GitHub branch updates: ${{ steps.delete_stuff.outputs.branch_update }}"
          payload: |
            {"text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [{"type": "section","text": 
            {"type": "mrkdwn","text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"}}]}
        
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
